workflows:
  mystic_tarot_static_export:
    name: Mystic Tarot Static Export
    max_build_duration: 60
    environment:
      node: 18
      vars:
        CI: "true"
    cache:
      cache_paths:
        - $HOME/.npm
    scripts:
      - name: Install dependencies
        script: |
          set -euo pipefail
          npm install --no-progress
      - name: Lint
        script: |
          set -euo pipefail
          npm run lint
      - name: Type check
        script: |
          set -euo pipefail
          npm run type-check
      - name: Build static export for Capacitor shells
        script: |
          set -euo pipefail
          npm run build:app
      - name: Archive static export for download
        script: |
          set -euo pipefail
          tar -czf apps-web-out.tar.gz -C apps/web/out .
    artifacts:
      - apps-web-out.tar.gz
      - apps/web/out/**
    publishing:
      email:
        recipients:
          - highandhigh96@hotmail.com
          - fish760217@gmail.com
        notify:
          success: true
          failure: true
