workflows:
  mystic_tarot_static_export:
    name: Mystic Tarot Static Export
    max_build_duration: 60
    environment:
      node: 18
      vars:
        CI: 'true'
    cache:
      cache_paths:
        - $HOME/.npm
    scripts:
      - name: Install dependencies
        script: |
          npm install --no-progress

      - name: Lint
        script: |
          npm run lint
      - name: Type check
        script: |
          npm run type-check
      - name: Build static export for Capacitor shells
        script: |
          npm run build:app
      - name: Archive static export for download
        script: |
          tar -czf apps-web-out.tar.gz -C .next .
    artifacts:
      - apps-web-out.tar.gz
      - .next/**
    publishing:
      email:
        recipients:
          - highandhigh96@hotmail.com
          - fish760217@gmail.com
        notify:
          success: true
          failure: true

  mystic_tarot_ios:
    name: Mystic Tarot iOS
    max_build_duration: 120
    environment:
      node: 18
      xcode: latest
      cocoapods: default
      vars:
        CI: 'true'
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - name: Install dependencies
        script: |
          npm install --no-progress
      - name: Build and sync static export
        script: |
          npm run build:app
      - name: Update iOS dependencies
        script: |
          cd ios/App && pod install
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - highandhigh96@hotmail.com
          - fish760217@gmail.com
        notify:
          success: true
          failure: true

  mystic_tarot_android:
    name: Mystic Tarot Android
    max_build_duration: 120
    environment:
      node: 18
      java: 17
      vars:
        CI: 'true'
        CM_KEYSTORE: Encrypted(keystore)
        CM_KEYSTORE_PASSWORD: Encrypted(password)
        CM_KEY_ALIAS: upload
        CM_KEY_PASSWORD: Encrypted(password)
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/.gradle/caches
    scripts:
      - name: Install dependencies
        script: |
          npm install --no-progress
      - name: Build and sync static export
        script: |
          npm run build:app
      - name: Decode Android keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/upload-keystore.jks
          cp $CM_BUILD_DIR/upload-keystore.jks android/app/upload-keystore.jks
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
      - name: Build Android AAB
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - highandhigh96@hotmail.com
          - fish760217@gmail.com
        notify:
          success: true
          failure: true
