import type { Card } from './types';

// Major Arcana Cards with multi-language support
export const majorArcanaCards: Card[] = [
  {
    id: 'fool',
    name: 'The Fool',
    nameTranslations: {
      zh: '愚者',
      es: 'El Loco',
      fr: 'Le Mat',
      de: 'Der Narr',
      id: 'Si Bodoh',
      vi: 'Kẻ Ngốc',
      th: 'คนโง่',
      ja: '愚者',
      ko: '바보',
      'pt-BR': 'O Louco',
      'pt-PT': 'O Louco',
      it: 'Il Matto',
      ru: 'Дурак',
      tr: 'Deli',
      ar: 'الأحمق',
      hi: 'मूर्ख',
      fil: 'Ang Hangal',
      ms: 'Si Bodoh',
      pl: 'Błazen'
    },
    type: 'major',
    meaning: 'New beginnings, innocence, spontaneity, free spirit',
    meaningReversed: 'Recklessness, taken advantage of, inconsideration',
    imagePath: '/cards/fool.svg'
  },
  {
    id: 'magician',
    name: 'The Magician',
    nameTranslations: {
      zh: '魔术师',
      es: 'El Mago',
      fr: 'Le Bateleur',
      de: 'Der Magier',
      id: 'Pesulap',
      vi: 'Ảo Thuật Gia',
      th: 'นักมายากล',
      ja: '魔術師',
      ko: '마법사',
      'pt-BR': 'O Mago',
      'pt-PT': 'O Mago',
      it: 'Il Mago',
      ru: 'Маг',
      tr: 'Büyücü',
      ar: 'الساحر',
      hi: 'जादूगर',
      fil: 'Ang Salamangkero',
      ms: 'Ahli Sihir',
      pl: 'Mag'
    },
    type: 'major',
    meaning: 'Willpower, desire, creation, manifestation',
    meaningReversed: 'Manipulation, poor planning, untapped talents',
    imagePath: '/cards/magician.svg'
  },
  {
    id: 'high-priestess',
    name: 'The High Priestess',
    nameTranslations: {
      zh: '女祭司',
      es: 'La Sacerdotisa',
      fr: 'La Papesse',
      de: 'Die Hohepriesterin',
      id: 'Pendeta Wanita',
      vi: 'Nữ Tế',
      th: 'นักบวชหญิง',
      ja: '女教皇',
      ko: '여사제',
      'pt-BR': 'A Sacerdotisa',
      'pt-PT': 'A Sacerdotisa',
      it: 'La Papessa',
      ru: 'Верховная Жрица',
      tr: 'Yüksek Rahibe',
      ar: 'الكاهنة العليا',
      hi: 'उच्च पुजारिन',
      fil: 'Ang Mataas na Pari',
      ms: 'Pendeta Tinggi',
      pl: 'Arcykaplanka'
    },
    type: 'major',
    meaning: 'Intuitive, unconscious, inner voice',
    meaningReversed: 'Lack of center, lost inner voice, repressed feelings',
    imagePath: '/cards/high-priestess.svg'
  },
  {
    id: 'empress',
    name: 'The Empress',
    nameTranslations: {
      zh: '皇后',
      es: 'La Emperatriz',
      fr: 'L\'Impératrice',
      de: 'Die Kaiserin',
      id: 'Permaisuri',
      vi: 'Nữ Hoàng',
      th: 'จักรพรรดินี',
      ja: '女帝',
      ko: '여제',
      'pt-BR': 'A Imperatriz',
      'pt-PT': 'A Imperatriz',
      it: 'L\'Imperatrice',
      ru: 'Императрица',
      tr: 'İmparatoriçe',
      ar: 'الإمبراطورة',
      hi: 'महारानी',
      fil: 'Ang Emperatris',
      ms: 'Permaisuri',
      pl: 'Cesarzowa'
    },
    type: 'major',
    meaning: 'Motherhood, fertility, nature',
    meaningReversed: 'Dependence, smothering, emptiness, nosiness',
    imagePath: '/cards/empress.svg'
  },
  {
    id: 'emperor',
    name: 'The Emperor',
    nameTranslations: {
      zh: '皇帝',
      es: 'El Emperador',
      fr: 'L\'Empereur',
      de: 'Der Kaiser',
      id: 'Kaisar',
      vi: 'Hoàng Đế',
      th: 'จักรพรรดิ',
      ja: '皇帝',
      ko: '황제',
      'pt-BR': 'O Imperador',
      'pt-PT': 'O Imperador',
      it: 'L\'Imperatore',
      ru: 'Император',
      tr: 'İmparator',
      ar: 'الإمبراطور',
      hi: 'सम्राट',
      fil: 'Ang Emperador',
      ms: 'Maharaja',
      pl: 'Cesarz'
    },
    type: 'major',
    meaning: 'Authority, structure, control, fatherhood',
    meaningReversed: 'Tyranny, rigidity, coldness',
    imagePath: '/cards/emperor.svg'
  },
  {
    id: 'hierophant',
    name: 'The Hierophant',
    nameTranslations: {
      zh: '教皇',
      es: 'El Hierofante',
      fr: 'Le Pape',
      de: 'Der Hierophant',
      id: 'Hierofan',
      vi: 'Giáo Hoàng',
      th: 'นักบวชสูง',
      ja: '法王',
      ko: '교황',
      'pt-BR': 'O Hierofante',
      'pt-PT': 'O Hierofante',
      it: 'Il Papa',
      ru: 'Иерофант',
      tr: 'Hierophant',
      ar: 'الهيروفانت',
      hi: 'महायाजक',
      fil: 'Ang Hierophante',
      ms: 'Hierofan',
      pl: 'Hierofant'
    },
    type: 'major',
    meaning: 'Tradition, conformity, morality, ethics',
    meaningReversed: 'Rebellion, subversiveness, new approaches',
    imagePath: '/cards/hierophant.svg'
  },
  {
    id: 'lovers',
    name: 'The Lovers',
    nameTranslations: {
      zh: '恋人',
      es: 'Los Enamorados',
      fr: 'L\'Amoureux',
      de: 'Die Liebenden',
      id: 'Kekasih',
      vi: 'Đôi Tình Nhân',
      th: 'คู่รัก',
      ja: '恋人',
      ko: '연인',
      'pt-BR': 'Os Namorados',
      'pt-PT': 'Os Namorados',
      it: 'Gli Amanti',
      ru: 'Влюбленные',
      tr: 'Aşıklar',
      ar: 'العشاق',
      hi: 'प्रेमी',
      fil: 'Ang mga Mangingibig',
      ms: 'Pasangan Kekasih',
      pl: 'Kochankowie'
    },
    type: 'major',
    meaning: 'Partnerships, duality, union',
    meaningReversed: 'Loss of balance, one-sidedness, disharmony',
    imagePath: '/cards/lovers.svg'
  },
  {
    id: 'chariot',
    name: 'The Chariot',
    nameTranslations: {
      zh: '战车',
      es: 'El Carro',
      fr: 'Le Chariot',
      de: 'Der Wagen',
      id: 'Kereta Perang',
      vi: 'Xe Chiến',
      th: 'รถรบ',
      ja: '戦車',
      ko: '전차',
      'pt-BR': 'O Carro',
      'pt-PT': 'O Carro',
      it: 'Il Carro',
      ru: 'Колесница',
      tr: 'Savaş Arabası',
      ar: 'العربة',
      hi: 'रथ',
      fil: 'Ang Karwahe',
      ms: 'Kereta Kuda',
      pl: 'Rydwan'
    },
    type: 'major',
    meaning: 'Direction, control, willpower',
    meaningReversed: 'Lack of control, lack of direction, aggression',
    imagePath: '/cards/chariot.svg'
  },
  {
    id: 'strength',
    name: 'Strength',
    nameTranslations: {
      zh: '力量',
      es: 'La Fuerza',
      fr: 'La Force',
      de: 'Die Kraft',
      id: 'Kekuatan',
      vi: 'Sức Mạnh',
      th: 'พลัง',
      ja: '力',
      ko: '힘',
      'pt-BR': 'A Força',
      'pt-PT': 'A Força',
      it: 'La Forza',
      ru: 'Сила',
      tr: 'Güç',
      ar: 'القوة',
      hi: 'शक्ति',
      fil: 'Ang Lakas',
      ms: 'Kekuatan',
      pl: 'Siła'
    },
    type: 'major',
    meaning: 'Inner strength, bravery, compassion, focus',
    meaningReversed: 'Self doubt, weakness, insecurity',
    imagePath: '/cards/strength.svg'
  },
  {
    id: 'hermit',
    name: 'The Hermit',
    nameTranslations: {
      zh: '隐士',
      es: 'El Ermitaño',
      fr: 'L\'Ermite',
      de: 'Der Eremit',
      id: 'Pertapa',
      vi: 'Ẩn Sĩ',
      th: 'นักพรต',
      ja: '隠者',
      ko: '은둔자',
      'pt-BR': 'O Eremita',
      'pt-PT': 'O Eremita',
      it: 'L\'Eremita',
      ru: 'Отшельник',
      tr: 'Ermiş',
      ar: 'الناسك',
      hi: 'संन्यासी',
      fil: 'Ang Ermitanyo',
      ms: 'Pertapa',
      pl: 'Eremita'
    },
    type: 'major',
    meaning: 'Soul searching, introspection, inner guidance',
    meaningReversed: 'Isolation, loneliness, withdrawal',
    imagePath: '/cards/hermit.svg'
  },
  {
    id: 'wheel-of-fortune',
    name: 'Wheel of Fortune',
    nameTranslations: {
      zh: '命运之轮',
      es: 'La Rueda de la Fortuna',
      fr: 'La Roue de Fortune',
      de: 'Das Rad des Schicksals',
      id: 'Roda Keberuntungan',
      vi: 'Bánh Xe Vận Mệnh',
      th: 'ล้อแห่งโชคชะตา',
      ja: '運命の輪',
      ko: '운명의 수레바퀴',
      'pt-BR': 'A Roda da Fortuna',
      'pt-PT': 'A Roda da Fortuna',
      it: 'La Ruota della Fortuna',
      ru: 'Колесо Фортуны',
      tr: 'Talih Çarkı',
      ar: 'عجلة الحظ',
      hi: 'भाग्य का चक्र',
      fil: 'Ang Gulong ng Kapalaran',
      ms: 'Roda Nasib',
      pl: 'Koło Fortuny'
    },
    type: 'major',
    meaning: 'Change, cycles, inevitable fate',
    meaningReversed: 'No control, clinging to control, bad luck',
    imagePath: '/cards/wheel-of-fortune.svg'
  },
  {
    id: 'justice',
    name: 'Justice',
    nameTranslations: {
      zh: '正义',
      es: 'La Justicia',
      fr: 'La Justice',
      de: 'Die Gerechtigkeit',
      id: 'Keadilan',
      vi: 'Công Lý',
      th: 'ความยุติธรรม',
      ja: '正義',
      ko: '정의',
      'pt-BR': 'A Justiça',
      'pt-PT': 'A Justiça',
      it: 'La Giustizia',
      ru: 'Правосудие',
      tr: 'Adalet',
      ar: 'العدالة',
      hi: 'न्याय',
      fil: 'Ang Katarungan',
      ms: 'Keadilan',
      pl: 'Sprawiedliwość'
    },
    type: 'major',
    meaning: 'Cause and effect, clarity, truth',
    meaningReversed: 'Dishonesty, unaccountability, unfairness',
    imagePath: '/cards/justice.svg'
  },
  {
    id: 'hanged-man',
    name: 'The Hanged Man',
    nameTranslations: {
      zh: '吊人',
      es: 'El Colgado',
      fr: 'Le Pendu',
      de: 'Der Gehängte',
      id: 'Orang Tergantung',
      vi: 'Người Bị Treo',
      th: 'คนแขวน',
      ja: '吊された男',
      ko: '매달린 남자',
      'pt-BR': 'O Enforcado',
      'pt-PT': 'O Enforcado',
      it: 'L\'Appeso',
      ru: 'Повешенный',
      tr: 'Asılan Adam',
      ar: 'الرجل المعلق',
      hi: 'लटका हुआ आदमी',
      fil: 'Ang Nakabitin na Lalaki',
      ms: 'Lelaki Tergantung',
      pl: 'Wisielec'
    },
    type: 'major',
    meaning: 'Sacrifice, release, martyrdom',
    meaningReversed: 'Stalling, needless sacrifice, fear of sacrifice',
    imagePath: '/cards/hanged-man.svg'
  },
  {
    id: 'death',
    name: 'Death',
    nameTranslations: {
      zh: '死神',
      es: 'La Muerte',
      fr: 'La Mort',
      de: 'Der Tod',
      id: 'Kematian',
      vi: 'Cái Chết',
      th: 'ความตาย',
      ja: '死神',
      ko: '죽음',
      'pt-BR': 'A Morte',
      'pt-PT': 'A Morte',
      it: 'La Morte',
      ru: 'Смерть',
      tr: 'Ölüm',
      ar: 'الموت',
      hi: 'मृत्यु',
      fil: 'Ang Kamatayan',
      ms: 'Kematian',
      pl: 'Śmierć'
    },
    type: 'major',
    meaning: 'Transformation, transition, change',
    meaningReversed: 'Resistance to change, personal transformation, inner purging',
    imagePath: '/cards/death.svg'
  },
  {
    id: 'temperance',
    name: 'Temperance',
    nameTranslations: {
      zh: '节制',
      es: 'La Templanza',
      fr: 'Tempérance',
      de: 'Die Mäßigkeit',
      id: 'Kesederhanaan',
      vi: 'Sự Tiết Chế',
      th: 'ความพอเพียง',
      ja: '節制',
      ko: '절제',
      'pt-BR': 'A Temperança',
      'pt-PT': 'A Temperança',
      it: 'La Temperanza',
      ru: 'Умеренность',
      tr: 'Ölçülülük',
      ar: 'الاعتدال',
      hi: 'संयम',
      fil: 'Ang Katamtaman',
      ms: 'Kesederhanaan',
      pl: 'Umiarkowanie'
    },
    type: 'major',
    meaning: 'Middle path, patience, finding meaning',
    meaningReversed: 'Extremes, excess, lack of balance',
    imagePath: '/cards/temperance.svg'
  },
  {
    id: 'devil',
    name: 'The Devil',
    nameTranslations: {
      zh: '恶魔',
      es: 'El Diablo',
      fr: 'Le Diable',
      de: 'Der Teufel',
      id: 'Iblis',
      vi: 'Ác Quỷ',
      th: 'ปีศาจ',
      ja: '悪魔',
      ko: '악마',
      'pt-BR': 'O Diabo',
      'pt-PT': 'O Diabo',
      it: 'Il Diavolo',
      ru: 'Дьявол',
      tr: 'Şeytan',
      ar: 'الشيطان',
      hi: 'शैतान',
      fil: 'Ang Demonyo',
      ms: 'Syaitan',
      pl: 'Diabeł'
    },
    type: 'major',
    meaning: 'Addiction, materialism, playfulness',
    meaningReversed: 'Freedom, release, restoring control',
    imagePath: '/cards/devil.svg'
  },
  {
    id: 'tower',
    name: 'The Tower',
    nameTranslations: {
      zh: '塔',
      es: 'La Torre',
      fr: 'La Maison Dieu',
      de: 'Der Turm',
      id: 'Menara',
      vi: 'Tháp',
      th: 'หอคอย',
      ja: '塔',
      ko: '탑',
      'pt-BR': 'A Torre',
      'pt-PT': 'A Torre',
      it: 'La Torre',
      ru: 'Башня',
      tr: 'Kule',
      ar: 'البرج',
      hi: 'मीनार',
      fil: 'Ang Tore',
      ms: 'Menara',
      pl: 'Wieża'
    },
    type: 'major',
    meaning: 'Sudden upheaval, broken pride, disaster',
    meaningReversed: 'Disaster avoided, delayed disaster, fear of suffering',
    imagePath: '/cards/tower.svg'
  },
  {
    id: 'star',
    name: 'The Star',
    nameTranslations: {
      zh: '星星',
      es: 'La Estrella',
      fr: 'L\'Étoile',
      de: 'Der Stern',
      id: 'Bintang',
      vi: 'Ngôi Sao',
      th: 'ดาว',
      ja: '星',
      ko: '별',
      'pt-BR': 'A Estrela',
      'pt-PT': 'A Estrela',
      it: 'La Stella',
      ru: 'Звезда',
      tr: 'Yıldız',
      ar: 'النجمة',
      hi: 'तारा',
      fil: 'Ang Bituin',
      ms: 'Bintang',
      pl: 'Gwiazda'
    },
    type: 'major',
    meaning: 'Hope, faith, purpose, renewal, spirituality',
    meaningReversed: 'Faithlessness, discouragement, self-trust, disconnection',
    imagePath: '/cards/star.svg'
  },
  {
    id: 'moon',
    name: 'The Moon',
    nameTranslations: {
      zh: '月亮',
      es: 'La Luna',
      fr: 'La Lune',
      de: 'Der Mond',
      id: 'Bulan',
      vi: 'Mặt Trăng',
      th: 'ดวงจันทร์',
      ja: '月',
      ko: '달',
      'pt-BR': 'A Lua',
      'pt-PT': 'A Lua',
      it: 'La Luna',
      ru: 'Луна',
      tr: 'Ay',
      ar: 'القمر',
      hi: 'चांद',
      fil: 'Ang Buwan',
      ms: 'Bulan',
      pl: 'Księżyc'
    },
    type: 'major',
    meaning: 'Unconscious, illusions, intuition',
    meaningReversed: 'Confusion, fear, misinterpretation',
    imagePath: '/cards/moon.svg'
  },
  {
    id: 'sun',
    name: 'The Sun',
    nameTranslations: {
      zh: '太阳',
      es: 'El Sol',
      fr: 'Le Soleil',
      de: 'Die Sonne',
      id: 'Matahari',
      vi: 'Mặt Trời',
      th: 'ดวงอาทิตย์',
      ja: '太陽',
      ko: '태양',
      'pt-BR': 'O Sol',
      'pt-PT': 'O Sol',
      it: 'Il Sole',
      ru: 'Солнце',
      tr: 'Güneş',
      ar: 'الشمس',
      hi: 'सूरज',
      fil: 'Ang Araw',
      ms: 'Matahari',
      pl: 'Słońce'
    },
    type: 'major',
    meaning: 'Joy, success, celebration, positivity',
    meaningReversed: 'Negativity, depression, sadness',
    imagePath: '/cards/sun.svg'
  },
  {
    id: 'judgement',
    name: 'Judgement',
    nameTranslations: {
      zh: '审判',
      es: 'El Juicio',
      fr: 'Le Jugement',
      de: 'Das Gericht',
      id: 'Penghakiman',
      vi: 'Phán Xét',
      th: 'การตัดสิน',
      ja: '審判',
      ko: '심판',
      'pt-BR': 'O Julgamento',
      'pt-PT': 'O Julgamento',
      it: 'Il Giudizio',
      ru: 'Суд',
      tr: 'Mahkeme',
      ar: 'الحكم',
      hi: 'न्याय',
      fil: 'Ang Paghuhukom',
      ms: 'Penghakiman',
      pl: 'Sąd'
    },
    type: 'major',
    meaning: 'Reflection, reckoning, awakening',
    meaningReversed: 'Self doubt, inner critic, ignoring the call',
    imagePath: '/cards/judgement.svg'
  },
  {
    id: 'world',
    name: 'The World',
    nameTranslations: {
      zh: '世界',
      es: 'El Mundo',
      fr: 'Le Monde',
      de: 'Die Welt',
      id: 'Dunia',
      vi: 'Thế Giới',
      th: 'โลก',
      ja: '世界',
      ko: '세계',
      'pt-BR': 'O Mundo',
      'pt-PT': 'O Mundo',
      it: 'Il Mondo',
      ru: 'Мир',
      tr: 'Dünya',
      ar: 'العالم',
      hi: 'संसार',
      fil: 'Ang Mundo',
      ms: 'Dunia',
      pl: 'Świat'
    },
    type: 'major',
    meaning: 'Fulfillment, harmony, completion',
    meaningReversed: 'Incomplete, no closure, lack of achievement',
    imagePath: '/cards/world.svg'
  }
];

// Placeholder for Minor Arcana - full implementation would include all 56 cards
export const minorArcanaCards: Card[] = [
  // Cups (14 cards)
  {
    id: 'ace-of-cups',
    name: 'Ace of Cups',
    suit: 'cups',
    number: 1,
    type: 'minor',
    meaning: 'New love, emotional awakening, creativity',
    meaningReversed: 'Emotional blockages, emptiness, lack of love',
    imagePath: '/cards/ace-of-cups.svg'
  },
  // TODO: Add remaining 13 Cups cards
  
  // Wands (14 cards)
  {
    id: 'ace-of-wands',
    name: 'Ace of Wands',
    suit: 'wands',
    number: 1,
    type: 'minor',
    meaning: 'New beginnings, inspiration, creative energy',
    meaningReversed: 'Lack of energy, delays, false starts',
    imagePath: '/cards/ace-of-wands.svg'
  },
  // TODO: Add remaining 13 Wands cards
  
  // Swords (14 cards)
  {
    id: 'ace-of-swords',
    name: 'Ace of Swords',
    suit: 'swords',
    number: 1,
    type: 'minor',
    meaning: 'Mental clarity, breakthrough, new ideas',
    meaningReversed: 'Confusion, mental fog, lack of clarity',
    imagePath: '/cards/ace-of-swords.svg'
  },
  // TODO: Add remaining 13 Swords cards
  
  // Pentacles (14 cards)
  {
    id: 'ace-of-pentacles',
    name: 'Ace of Pentacles',
    suit: 'pentacles',
    number: 1,
    type: 'minor',
    meaning: 'New financial opportunity, manifestation, prosperity',
    meaningReversed: 'Lost opportunity, lack of planning, bad investment',
    imagePath: '/cards/ace-of-pentacles.svg'
  },
  // TODO: Add remaining 13 Pentacles cards
];

export const allCards: Card[] = [...majorArcanaCards, ...minorArcanaCards];

export function getCardById(id: string): Card | undefined {
  return allCards.find(card => card.id === id);
}

export function getRandomCards(count: number): Card[] {
  const shuffled = [...allCards].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}