import { Card } from './types'

// TODO: Future enrichment - add more detailed meanings, keywords, and imagery descriptions
export const TAROT_CARDS: Card[] = [
  // Major Arcana
  {
    id: 'fool',
    name: 'The Fool',
    arcanaType: 'Major',
    uprightMeaning: 'New beginnings, innocence, spontaneity, and free spirit.',
    reversedMeaning: 'Recklessness, taken advantage of, inconsideration, and foolishness.',
    image: '/cards/fool.svg',
  },
  {
    id: 'magician',
    name: 'The Magician',
    arcanaType: 'Major',
    uprightMeaning: 'Manifestation, resourcefulness, power, and inspired action.',
    reversedMeaning: 'Manipulation, poor planning, untapped talents, and trickery.',
    image: '/cards/magician.svg',
  },
  {
    id: 'high-priestess',
    name: 'The High Priestess',
    arcanaType: 'Major',
    uprightMeaning: 'Intuition, sacred knowledge, divine feminine, and subconscious mind.',
    reversedMeaning: 'Secrets, disconnected from intuition, withdrawal, and silence.',
    image: '/cards/high-priestess.svg',
  },
  {
    id: 'empress',
    name: 'The Empress',
    arcanaType: 'Major',
    uprightMeaning: 'Femininity, beauty, nature, nurturing, and abundance.',
    reversedMeaning: 'Creative block, dependence on others, smothering, and lack of growth.',
    image: '/cards/empress.svg',
  },
  {
    id: 'emperor',
    name: 'The Emperor',
    arcanaType: 'Major',
    uprightMeaning: 'Authority, establishment, structure, father figure, and control.',
    reversedMeaning: 'Tyranny, rigidity, coldness, and loss of authority.',
    image: '/cards/emperor.svg',
  },
  {
    id: 'hierophant',
    name: 'The Hierophant',
    arcanaType: 'Major',
    uprightMeaning: 'Spiritual wisdom, religious beliefs, conformity, and tradition.',
    reversedMeaning: 'Personal beliefs, freedom, challenging the status quo, and rebellion.',
    image: '/cards/hierophant.svg',
  },
  {
    id: 'lovers',
    name: 'The Lovers',
    arcanaType: 'Major',
    uprightMeaning: 'Love, harmony, relationships, values alignment, and choices.',
    reversedMeaning: 'Self-love, disharmony, imbalance, and misalignment of values.',
    image: '/cards/lovers.svg',
  },
  {
    id: 'chariot',
    name: 'The Chariot',
    arcanaType: 'Major',
    uprightMeaning: 'Control, willpower, success, determination, and direction.',
    reversedMeaning: 'Self-discipline, opposition, lack of direction, and aggression.',
    image: '/cards/chariot.svg',
  },
  {
    id: 'strength',
    name: 'Strength',
    arcanaType: 'Major',
    uprightMeaning: 'Strength, courage, persuasion, influence, and compassion.',
    reversedMeaning: 'Self-doubt, low energy, raw emotion, and inner strength.',
    image: '/cards/strength.svg',
  },
  {
    id: 'hermit',
    name: 'The Hermit',
    arcanaType: 'Major',
    uprightMeaning: 'Soul searching, introspection, inner guidance, and solitude.',
    reversedMeaning: 'Isolation, loneliness, withdrawal, and seeking outside guidance.',
    image: '/cards/hermit.svg',
  },
  {
    id: 'wheel-of-fortune',
    name: 'Wheel of Fortune',
    arcanaType: 'Major',
    uprightMeaning: 'Good luck, karma, life cycles, destiny, and turning point.',
    reversedMeaning: 'Bad luck, lack of control, clinging to control, and bad timing.',
    image: '/cards/wheel-of-fortune.svg',
  },
  {
    id: 'justice',
    name: 'Justice',
    arcanaType: 'Major',
    uprightMeaning: 'Justice, fairness, truth, cause and effect, and law.',
    reversedMeaning: 'Unfairness, lack of accountability, dishonesty, and bias.',
    image: '/cards/justice.svg',
  },
  {
    id: 'hanged-man',
    name: 'The Hanged Man',
    arcanaType: 'Major',
    uprightMeaning: 'Suspension, restriction, letting go, sacrifice, and martyrdom.',
    reversedMeaning: 'Delays, resistance, stalling, and indecision.',
    image: '/cards/hanged-man.svg',
  },
  {
    id: 'death',
    name: 'Death',
    arcanaType: 'Major',
    uprightMeaning: 'Endings, change, transformation, transition, and new beginnings.',
    reversedMeaning: 'Resistance to change, fear of change, stagnation, and decay.',
    image: '/cards/death.svg',
  },
  {
    id: 'temperance',
    name: 'Temperance',
    arcanaType: 'Major',
    uprightMeaning: 'Balance, moderation, patience, purpose, and meaning.',
    reversedMeaning: 'Imbalance, excess, extremes, and lack of long-term vision.',
    image: '/cards/temperance.svg',
  },
  {
    id: 'devil',
    name: 'The Devil',
    arcanaType: 'Major',
    uprightMeaning: 'Bondage, addiction, sexuality, materialism, and playfulness.',
    reversedMeaning: 'Releasing limiting beliefs, exploring dark thoughts, and detachment.',
    image: '/cards/devil.svg',
  },
  {
    id: 'tower',
    name: 'The Tower',
    arcanaType: 'Major',
    uprightMeaning: 'Sudden change, upheaval, chaos, revelation, and awakening.',
    reversedMeaning: 'Personal transformation, fear of change, and avoiding disaster.',
    image: '/cards/tower.svg',
  },
  {
    id: 'star',
    name: 'The Star',
    arcanaType: 'Major',
    uprightMeaning: 'Hope, faith, purpose, renewal, and spirituality.',
    reversedMeaning: 'Lack of faith, despair, self-trust, and disconnection.',
    image: '/cards/star.svg',
  },
  {
    id: 'moon',
    name: 'The Moon',
    arcanaType: 'Major',
    uprightMeaning: 'Illusion, fear, anxiety, subconscious, and intuition.',
    reversedMeaning: 'Release of fear, repressed emotion, and inner confusion.',
    image: '/cards/moon.svg',
  },
  {
    id: 'sun',
    name: 'The Sun',
    arcanaType: 'Major',
    uprightMeaning: 'Positivity, fun, warmth, success, and vitality.',
    reversedMeaning: 'Inner child, feeling down, overly optimistic, and unrealistic.',
    image: '/cards/sun.svg',
  },
  {
    id: 'judgement',
    name: 'Judgement',
    arcanaType: 'Major',
    uprightMeaning: 'Judgement, rebirth, inner calling, absolution, and reflection.',
    reversedMeaning: 'Self-doubt, inner critic, ignoring the call, and lack of self-awareness.',
    image: '/cards/judgement.svg',
  },
  {
    id: 'world',
    name: 'The World',
    arcanaType: 'Major',
    uprightMeaning: 'Completion, integration, accomplishment, and travel.',
    reversedMeaning: 'Seeking personal closure, stagnation, and lack of achievement.',
    image: '/cards/world.svg',
  },

  // Minor Arcana - Cups
  {
    id: 'ace-of-cups',
    name: 'Ace of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    number: 1,
    uprightMeaning: 'Love, new relationships, compassion, and creativity.',
    reversedMeaning: 'Self-love, intuition, repressed emotions, and emptiness.',
    image: '/cards/ace-of-cups.svg',
  },
  {
    id: 'two-of-cups',
    name: 'Two of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    number: 2,
    uprightMeaning: 'Unified love, partnership, mutual attraction, and relationships.',
    reversedMeaning: 'Self-love, break-ups, disharmony, and distrust.',
    image: '/cards/two-of-cups.svg',
  },
  {
    id: 'three-of-cups',
    name: 'Three of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    number: 3,
    uprightMeaning: 'Celebration, friendship, creativity, and collaborations.',
    reversedMeaning: 'Independence, alone time, hardcore partying, and creative blocks.',
    image: '/cards/three-of-cups.svg',
  },
  {
    id: 'four-of-cups',
    name: 'Four of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    number: 4,
    uprightMeaning: 'Meditation, contemplation, apathy, and reevaluation.',
    reversedMeaning: 'Retreat, withdrawal, checking in for self-care, and soul-searching.',
    image: '/cards/four-of-cups.svg',
  },
  {
    id: 'five-of-cups',
    name: 'Five of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    number: 5,
    uprightMeaning: 'Regret, failure, disappointment, and pessimism.',
    reversedMeaning: 'Personal setbacks, self-forgiveness, moving on, and acceptance.',
    image: '/cards/five-of-cups.svg',
  },
  {
    id: 'six-of-cups',
    name: 'Six of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    number: 6,
    uprightMeaning: 'Revisiting the past, childhood memories, innocence, and joy.',
    reversedMeaning: 'Living in the past, forgiveness, lacking playfulness, and being stuck.',
    image: '/cards/six-of-cups.svg',
  },
  {
    id: 'seven-of-cups',
    name: 'Seven of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    number: 7,
    uprightMeaning: 'Opportunities, choices, wishful thinking, and illusion.',
    reversedMeaning: 'Alignment, personal values, overwhelmed by choices, and lack of options.',
    image: '/cards/seven-of-cups.svg',
  },
  {
    id: 'eight-of-cups',
    name: 'Eight of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    number: 8,
    uprightMeaning: 'Disappointment, abandonment, withdrawal, and escapism.',
    reversedMeaning: 'Trying one more time, indecision, aimless drifting, and confusion.',
    image: '/cards/eight-of-cups.svg',
  },
  {
    id: 'nine-of-cups',
    name: 'Nine of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    number: 9,
    uprightMeaning: 'Contentment, satisfaction, gratitude, and wish fulfillment.',
    reversedMeaning: 'Inner happiness, materialism, dissatisfaction, and overindulgence.',
    image: '/cards/nine-of-cups.svg',
  },
  {
    id: 'ten-of-cups',
    name: 'Ten of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    number: 10,
    uprightMeaning: 'Divine love, blissful relationships, harmony, and alignment.',
    reversedMeaning: 'Disconnection, misaligned values, struggling relationships, and disharmony.',
    image: '/cards/ten-of-cups.svg',
  },
  {
    id: 'page-of-cups',
    name: 'Page of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    uprightMeaning: 'Creative opportunities, intuitive messages, curiosity, and possibility.',
    reversedMeaning: 'New ideas, doubting intuition, creative blocks, and emotional immaturity.',
    image: '/cards/page-of-cups.svg',
  },
  {
    id: 'knight-of-cups',
    name: 'Knight of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    uprightMeaning: 'Creativity, romance, charm, imagination, and beauty.',
    reversedMeaning: 'Overactive imagination, unrealistic, jealousy, and moodiness.',
    image: '/cards/knight-of-cups.svg',
  },
  {
    id: 'queen-of-cups',
    name: 'Queen of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    uprightMeaning: 'Compassionate, caring, emotionally stable, intuitive, and in flow.',
    reversedMeaning: 'Inner feelings, self-care, self-love, and co-dependency.',
    image: '/cards/queen-of-cups.svg',
  },
  {
    id: 'king-of-cups',
    name: 'King of Cups',
    arcanaType: 'Minor',
    suit: 'Cups',
    uprightMeaning: 'Emotionally balanced, compassionate, diplomatic, and wise.',
    reversedMeaning: 'Self-compassion, inner feelings, moodiness, and emotionally manipulative.',
    image: '/cards/king-of-cups.svg',
  },

  // Minor Arcana - Wands
  {
    id: 'ace-of-wands',
    name: 'Ace of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    number: 1,
    uprightMeaning: 'Inspiration, new opportunities, growth, and potential.',
    reversedMeaning: 'An emerging idea, lack of direction, distractions, and delays.',
    image: '/cards/ace-of-wands.svg',
  },
  {
    id: 'two-of-wands',
    name: 'Two of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    number: 2,
    uprightMeaning: 'Future planning, making decisions, leaving comfort zone, and personal goals.',
    reversedMeaning: 'Personal goals, inner alignment, fear of unknown, and lack of planning.',
    image: '/cards/two-of-wands.svg',
  },
  {
    id: 'three-of-wands',
    name: 'Three of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    number: 3,
    uprightMeaning: 'Expansion, foresight, overseas opportunities, and leadership.',
    reversedMeaning: 'Playing small, lack of foresight, unexpected delays, and frustration.',
    image: '/cards/three-of-wands.svg',
  },
  {
    id: 'four-of-wands',
    name: 'Four of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    number: 4,
    uprightMeaning: 'Celebration, joy, harmony, relaxation, and homecoming.',
    reversedMeaning: 'Personal celebration, inner harmony, conflict with others, and transition.',
    image: '/cards/four-of-wands.svg',
  },
  {
    id: 'five-of-wands',
    name: 'Five of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    number: 5,
    uprightMeaning: 'Conflict, disagreements, competition, tension, and diversity.',
    reversedMeaning: 'Inner conflict, conflict avoidance, tension release, and cooperation.',
    image: '/cards/five-of-wands.svg',
  },
  {
    id: 'six-of-wands',
    name: 'Six of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    number: 6,
    uprightMeaning: 'Success, public recognition, progress, self-confidence, and pride.',
    reversedMeaning: 'Private achievement, personal definition of success, fall from grace, and ego.',
    image: '/cards/six-of-wands.svg',
  },
  {
    id: 'seven-of-wands',
    name: 'Seven of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    number: 7,
    uprightMeaning: 'Challenge, competition, protection, perseverance, and maintaining control.',
    reversedMeaning: 'Exhaustion, giving up, overwhelmed, and feeling vulnerable.',
    image: '/cards/seven-of-wands.svg',
  },
  {
    id: 'eight-of-wands',
    name: 'Eight of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    number: 8,
    uprightMeaning: 'Swiftness, speed, progress, movement, and quick decisions.',
    reversedMeaning: 'Delays, frustration, resisting change, and internal alignment.',
    image: '/cards/eight-of-wands.svg',
  },
  {
    id: 'nine-of-wands',
    name: 'Nine of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    number: 9,
    uprightMeaning: 'Resilience, courage, persistence, test of faith, and boundaries.',
    reversedMeaning: 'Inner resources, struggle, overwhelm, and defensive.',
    image: '/cards/nine-of-wands.svg',
  },
  {
    id: 'ten-of-wands',
    name: 'Ten of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    number: 10,
    uprightMeaning: 'Burden, extra responsibility, hard work, completion, and achievement.',
    reversedMeaning: 'Doing it all, carrying the load, delegation, and release.',
    image: '/cards/ten-of-wands.svg',
  },
  {
    id: 'page-of-wands',
    name: 'Page of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    uprightMeaning: 'Inspiration, ideas, discovery, limitless potential, and free spirit.',
    reversedMeaning: 'Newly formed ideas, redirecting energy, self-limiting beliefs, and a spiritual path.',
    image: '/cards/page-of-wands.svg',
  },
  {
    id: 'knight-of-wands',
    name: 'Knight of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    uprightMeaning: 'Energy, passion, inspired action, adventure, and impulsiveness.',
    reversedMeaning: 'Passion project, haste, scattered energy, and delays.',
    image: '/cards/knight-of-wands.svg',
  },
  {
    id: 'queen-of-wands',
    name: 'Queen of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    uprightMeaning: 'Courage, confidence, independence, social butterfly, and determination.',
    reversedMeaning: 'Self-respect, self-confidence, introverted, and re-establish sense of self.',
    image: '/cards/queen-of-wands.svg',
  },
  {
    id: 'king-of-wands',
    name: 'King of Wands',
    arcanaType: 'Minor',
    suit: 'Wands',
    uprightMeaning: 'Natural leader, vision, entrepreneur, honour, and being in charge.',
    reversedMeaning: 'Impulsiveness, haste, ruthless, high expectations, and forceful.',
    image: '/cards/king-of-wands.svg',
  },

  // Minor Arcana - Swords
  {
    id: 'ace-of-swords',
    name: 'Ace of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    number: 1,
    uprightMeaning: 'Breakthrough, clarity, sharp mind, and new ideas.',
    reversedMeaning: 'Inner clarity, re-thinking an idea, clouded judgement, and confusion.',
    image: '/cards/ace-of-swords.svg',
  },
  {
    id: 'two-of-swords',
    name: 'Two of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    number: 2,
    uprightMeaning: 'Difficult decisions, weighing up options, an impasse, and avoidance.',
    reversedMeaning: 'Indecision, confusion, information overload, and stalemate.',
    image: '/cards/two-of-swords.svg',
  },
  {
    id: 'three-of-swords',
    name: 'Three of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    number: 3,
    uprightMeaning: 'Heartbreak, emotional pain, sorrow, grief, and hurt.',
    reversedMeaning: 'Negative self-talk, releasing pain, optimism, and forgiveness.',
    image: '/cards/three-of-swords.svg',
  },
  {
    id: 'four-of-swords',
    name: 'Four of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    number: 4,
    uprightMeaning: 'Rest, relaxation, meditation, contemplation, and recuperation.',
    reversedMeaning: 'Awakening, re-entering the world, restlessness, and burnout.',
    image: '/cards/four-of-swords.svg',
  },
  {
    id: 'five-of-swords',
    name: 'Five of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    number: 5,
    uprightMeaning: 'Conflict, disagreements, competition, defeat, and winning at all costs.',
    reversedMeaning: 'Reconciliation, making amends, past resentment, and desire to reconcile.',
    image: '/cards/five-of-swords.svg',
  },
  {
    id: 'six-of-swords',
    name: 'Six of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    number: 6,
    uprightMeaning: 'Transition, change, rite of passage, releasing baggage, and moving forward.',
    reversedMeaning: 'Personal transition, resistance to change, unfinished business, and emotional baggage.',
    image: '/cards/six-of-swords.svg',
  },
  {
    id: 'seven-of-swords',
    name: 'Seven of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    number: 7,
    uprightMeaning: 'Betrayal, deception, getting away with something, and acting strategically.',
    reversedMeaning: 'Imposter syndrome, self-deceit, keeping secrets, and coming clean.',
    image: '/cards/seven-of-swords.svg',
  },
  {
    id: 'eight-of-swords',
    name: 'Eight of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    number: 8,
    uprightMeaning: 'Negative thoughts, self-imposed restriction, imprisonment, and victim mentality.',
    reversedMeaning: 'Self-limiting beliefs, inner critic, releasing negative thoughts, and open to new perspectives.',
    image: '/cards/eight-of-swords.svg',
  },
  {
    id: 'nine-of-swords',
    name: 'Nine of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    number: 9,
    uprightMeaning: 'Anxiety, worry, fear, depression, and nightmares.',
    reversedMeaning: 'Inner turmoil, deep-seated fears, secrets, and releasing worry.',
    image: '/cards/nine-of-swords.svg',
  },
  {
    id: 'ten-of-swords',
    name: 'Ten of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    number: 10,
    uprightMeaning: 'Painful endings, deep wounds, betrayal, loss, and crisis.',
    reversedMeaning: 'Recovery, regeneration, resisting an inevitable end, and surviving disaster.',
    image: '/cards/ten-of-swords.svg',
  },
  {
    id: 'page-of-swords',
    name: 'Page of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    uprightMeaning: 'New ideas, curiosity, thirst for knowledge, new ways of communicating.',
    reversedMeaning: 'Self-expression, all talk and no action, haphazard action, and unfocused.',
    image: '/cards/page-of-swords.svg',
  },
  {
    id: 'knight-of-swords',
    name: 'Knight of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    uprightMeaning: 'Ambitious, action-oriented, driven to succeed, fast-thinking, and impatient.',
    reversedMeaning: 'Restless, unfocused, impulsive, burn-out, and scattered energy.',
    image: '/cards/knight-of-swords.svg',
  },
  {
    id: 'queen-of-swords',
    name: 'Queen of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    uprightMeaning: 'Independent, unbiased judgement, clear boundaries, and direct communication.',
    reversedMeaning: 'Overly-emotional, easily influenced, bitchy, and cold-hearted.',
    image: '/cards/queen-of-swords.svg',
  },
  {
    id: 'king-of-swords',
    name: 'King of Swords',
    arcanaType: 'Minor',
    suit: 'Swords',
    uprightMeaning: 'Mental clarity, intellectual power, authority, truth, and disciplined mind.',
    reversedMeaning: 'Quiet power, inner truth, misuse of power, and manipulative.',
    image: '/cards/king-of-swords.svg',
  },

  // Minor Arcana - Pentacles
  {
    id: 'ace-of-pentacles',
    name: 'Ace of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    number: 1,
    uprightMeaning: 'A new financial or career opportunity, manifestation, and abundance.',
    reversedMeaning: 'Lost opportunity, missed chance, lack of planning, and poor financial decisions.',
    image: '/cards/ace-of-pentacles.svg',
  },
  {
    id: 'two-of-pentacles',
    name: 'Two of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    number: 2,
    uprightMeaning: 'Multiple priorities, time management, prioritisation, and adaptability.',
    reversedMeaning: 'Over-committed, disorganisation, reprioritisation, and overwhelm.',
    image: '/cards/two-of-pentacles.svg',
  },
  {
    id: 'three-of-pentacles',
    name: 'Three of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    number: 3,
    uprightMeaning: 'Teamwork, collaboration, learning, and implementation.',
    reversedMeaning: 'Disharmony, misalignment, working alone, and lack of teamwork.',
    image: '/cards/three-of-pentacles.svg',
  },
  {
    id: 'four-of-pentacles',
    name: 'Four of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    number: 4,
    uprightMeaning: 'Saving money, security, conservatism, scarcity, and control.',
    reversedMeaning: 'Over-spending, greed, self-protection, and financial insecurity.',
    image: '/cards/four-of-pentacles.svg',
  },
  {
    id: 'five-of-pentacles',
    name: 'Five of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    number: 5,
    uprightMeaning: 'Financial loss, poverty, lack mindset, isolation, and worry.',
    reversedMeaning: 'Recovery from financial loss, spiritual poverty, and inner resources.',
    image: '/cards/five-of-pentacles.svg',
  },
  {
    id: 'six-of-pentacles',
    name: 'Six of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    number: 6,
    uprightMeaning: 'Giving, receiving, sharing wealth, generosity, and charity.',
    reversedMeaning: 'Self-care, unpaid debts, one-sided charity, and power dynamics.',
    image: '/cards/six-of-pentacles.svg',
  },
  {
    id: 'seven-of-pentacles',
    name: 'Seven of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    number: 7,
    uprightMeaning: 'Sustainable results, long-term view, reward for efforts, and perseverance.',
    reversedMeaning: 'Lack of rewards for efforts, impatience, and wanting quick results.',
    image: '/cards/seven-of-pentacles.svg',
  },
  {
    id: 'eight-of-pentacles',
    name: 'Eight of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    number: 8,
    uprightMeaning: 'Apprenticeship, repetitive tasks, mastery, skill development, and hard work.',
    reversedMeaning: 'Self-development, perfectionism, misdirected activity, and lack of motivation.',
    image: '/cards/eight-of-pentacles.svg',
  },
  {
    id: 'nine-of-pentacles',
    name: 'Nine of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    number: 9,
    uprightMeaning: 'Abundance, luxury, self-sufficiency, financial independence, and success.',
    reversedMeaning: 'Self-worth, over-investment in work, hustling, and work-life balance.',
    image: '/cards/nine-of-pentacles.svg',
  },
  {
    id: 'ten-of-pentacles',
    name: 'Ten of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    number: 10,
    uprightMeaning: 'Wealth, financial security, family, long-term success, and contribution.',
    reversedMeaning: 'The dark side of wealth, financial failure or loss, and financial instability.',
    image: '/cards/ten-of-pentacles.svg',
  },
  {
    id: 'page-of-pentacles',
    name: 'Page of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    uprightMeaning: 'Manifestation, financial opportunity, skill development, and progress.',
    reversedMeaning: 'Lack of progress, procrastination, learn from failure, and distracted.',
    image: '/cards/page-of-pentacles.svg',
  },
  {
    id: 'knight-of-pentacles',
    name: 'Knight of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    uprightMeaning: 'Hard work, productivity, routine, conservatism, and service-oriented.',
    reversedMeaning: 'Self-discipline, boredom, feeling stuck, perfectionism, and unreliable.',
    image: '/cards/knight-of-pentacles.svg',
  },
  {
    id: 'queen-of-pentacles',
    name: 'Queen of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    uprightMeaning: 'Nurturing, practical, providing financially, and a working parent.',
    reversedMeaning: 'Self-care, work-home conflict, and financial independence vs. dependence.',
    image: '/cards/queen-of-pentacles.svg',
  },
  {
    id: 'king-of-pentacles',
    name: 'King of Pentacles',
    arcanaType: 'Minor',
    suit: 'Pentacles',
    uprightMeaning: 'Financial success, business acumen, security, disciplined, and reliable.',
    reversedMeaning: 'Financially inept, obsessed with wealth, stubborn, and poor business judgement.',
    image: '/cards/king-of-pentacles.svg',
  },
]

export function getCardById(id: string): Card | undefined {
  return TAROT_CARDS.find((card) => card.id === id)
}

export function shuffleDeck(): Card[] {
  const shuffled = [...TAROT_CARDS]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}