import type { SpreadPosition } from './types';

export const pastPresentFutureSpread: SpreadPosition[] = [
  {
    id: 'past',
    name: 'Past',
    nameTranslations: {
      zh: '过去',
      es: 'Pasado',
      fr: 'Passé',
      de: 'Vergangenheit',
      id: 'Masa Lalu',
      vi: 'Quá khứ',
      th: 'อดีต',
      ja: '過去',
      ko: '과거',
      'pt-BR': 'Passado',
      'pt-PT': 'Passado',
      it: 'Passato',
      ru: 'Прошлое',
      tr: 'Geçmiş',
      ar: 'الماضي',
      hi: 'भूतकाल',
      fil: 'Nakaraan',
      ms: 'Masa Lalu',
      pl: 'Przeszłość'
    },
    description: 'Influences from your past that shape the current situation',
    descriptionTranslations: {
      zh: '来自过去的影响，塑造当前的局面',
      es: 'Influencias de tu pasado que moldean la situación actual',
      fr: 'Influences de votre passé qui façonnent la situation actuelle',
      de: 'Einflüsse aus Ihrer Vergangenheit, die die aktuelle Situation prägen',
      id: 'Pengaruh dari masa lalu yang membentuk situasi saat ini',
      vi: 'Những ảnh hưởng từ quá khứ định hình tình huống hiện tại',
      th: 'อิทธิพลจากอดีตที่หล่อหลอมสถานการณ์ปัจจุบัน',
      ja: '現在の状況を形作る過去からの影響',
      ko: '현재 상황을 형성하는 과거의 영향',
      'pt-BR': 'Influências do seu passado que moldam a situação atual',
      'pt-PT': 'Influências do seu passado que moldam a situação actual',
      it: 'Influenze dal tuo passato che plasmano la situazione attuale',
      ru: 'Влияние из вашего прошлого, формирующее текущую ситуацию',
      tr: 'Mevcut durumu şekillendiren geçmişinizden gelen etkiler',
      ar: 'التأثيرات من ماضيك التي تشكل الوضع الحالي',
      hi: 'आपके अतीत के प्रभाव जो वर्तमान स्थिति को आकार देते हैं',
      fil: 'Mga impluwensya mula sa inyong nakaraan na humuhubog sa kasalukuyang sitwasyon',
      ms: 'Pengaruh dari masa lalu yang membentuk situasi semasa',
      pl: 'Wpływy z przeszłości kształtujące obecną sytuację'
    }
  },
  {
    id: 'present',
    name: 'Present',
    nameTranslations: {
      zh: '现在',
      es: 'Presente',
      fr: 'Présent',
      de: 'Gegenwart',
      id: 'Sekarang',
      vi: 'Hiện tại',
      th: 'ปัจจุบัน',
      ja: '現在',
      ko: '현재',
      'pt-BR': 'Presente',
      'pt-PT': 'Presente',
      it: 'Presente',
      ru: 'Настоящее',
      tr: 'Şimdi',
      ar: 'الحاضر',
      hi: 'वर्तमान',
      fil: 'Kasalukuyan',
      ms: 'Masa Kini',
      pl: 'Teraźniejszość'
    },
    description: 'Your current situation and the energies surrounding you now',
    descriptionTranslations: {
      zh: '您当前的状况以及现在围绕您的能量',
      es: 'Tu situación actual y las energías que te rodean ahora',
      fr: 'Votre situation actuelle et les énergies qui vous entourent maintenant',
      de: 'Ihre aktuelle Situation und die Energien, die Sie jetzt umgeben',
      id: 'Situasi Anda saat ini dan energi yang mengelilingi Anda sekarang',
      vi: 'Tình huống hiện tại của bạn và những năng lượng xung quanh bạn',
      th: 'สถานการณ์ปัจจุบันและพลังงานที่อยู่รอบตัวคุณ',
      ja: 'あなたの現在の状況と今あなたを取り巻くエネルギー',
      ko: '현재 상황과 지금 당신을 둘러싼 에너지',
      'pt-BR': 'Sua situação atual e as energias ao seu redor agora',
      'pt-PT': 'A sua situação actual e as energias que o rodeiam agora',
      it: 'La tua situazione attuale e le energie che ti circondano ora',
      ru: 'Ваша текущая ситуация и энергии, окружающие вас сейчас',
      tr: 'Şu anki durumunuz ve şu anda sizi çevreleyen enerjiler',
      ar: 'وضعك الحالي والطاقات المحيطة بك الآن',
      hi: 'आपकी वर्तमान स्थिति और अब आपके चारों ओर की ऊर्जाएं',
      fil: 'Inyong kasalukuyang sitwasyon at mga enerhiyang nakapaligid sa inyo ngayon',
      ms: 'Situasi semasa anda dan tenaga yang mengelilingi anda sekarang',
      pl: 'Twoja obecna sytuacja i energie otaczające cię teraz'
    }
  },
  {
    id: 'future',
    name: 'Future',
    nameTranslations: {
      zh: '未来',
      es: 'Futuro',
      fr: 'Futur',
      de: 'Zukunft',
      id: 'Masa Depan',
      vi: 'Tương lai',
      th: 'อนาคต',
      ja: '未来',
      ko: '미래',
      'pt-BR': 'Futuro',
      'pt-PT': 'Futuro',
      it: 'Futuro',
      ru: 'Будущее',
      tr: 'Gelecek',
      ar: 'المستقبل',
      hi: 'भविष्य',
      fil: 'Hinaharap',
      ms: 'Masa Depan',
      pl: 'Przyszłość'
    },
    description: 'Potential outcomes and what the future may hold',
    descriptionTranslations: {
      zh: '潜在的结果以及未来可能带来的东西',
      es: 'Resultados potenciales y lo que el futuro puede deparar',
      fr: 'Résultats potentiels et ce que l\'avenir peut réserver',
      de: 'Mögliche Ergebnisse und was die Zukunft bringen kann',
      id: 'Hasil potensial dan apa yang mungkin terjadi di masa depan',
      vi: 'Kết quả tiềm năng và những gì tương lai có thể mang lại',
      th: 'ผลลัพธ์ที่เป็นไปได้และสิ่งที่อนาคตอาจนำมา',
      ja: '可能性のある結果と未来が持つもの',
      ko: '잠재적 결과와 미래가 가져올 것',
      'pt-BR': 'Resultados potenciais e o que o futuro pode reservar',
      'pt-PT': 'Resultados potenciais e o que o futuro pode reservar',
      it: 'Risultati potenziali e ciò che il futuro può riservare',
      ru: 'Потенциальные результаты и то, что может принести будущее',
      tr: 'Potansiyel sonuçlar ve geleceğin getirebilecekleri',
      ar: 'النتائج المحتملة وما قد يحمله المستقبل',
      hi: 'संभावित परिणाम और भविष्य में क्या हो सकता है',
      fil: 'Mga potensyal na kinalabasan at kung ano ang maaaring dalhin ng hinaharap',
      ms: 'Hasil yang berpotensi dan apa yang mungkin dibawa masa depan',
      pl: 'Potencjalne wyniki i to, co może przynieść przyszłość'
    }
  }
];