name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Verify release pipeline
        run: npm run release:verify
      - name: Upload Next.js build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: |
            .next
            apps/web/out
          if-no-files-found: ignore
